### ISSUE TITLE
RangeError thrown when aligning some genome sequences

### ISSUE THREAD

**Issue by hubgit** [ppillot/biomsalign#1]
I've been attempting to use this library to align some genome sequences, which would be very useful, but I'm finding that it throws a `RangeError` in some cases (like [this example](https://gist.github.com/hubgit/ee2572fc67778a045fe8ccb11d7ef23d)).

I can see a few places in `estringDifference` which return `undefined`, but I can't tell why that might be happening in this case.

**Comment by ppillot** [comment]
Thanks for your interest in the library. It is still early stages and rough around the edges.
I've reproduced your test case and noticed the same issue.
I've also done a second test, in a browser using a demo application, by copy/pasting the contents of the fasta files from your requests. In that second test, there is no RangeError thrown. As for the result...  some segments look decently aligned and some other stretches seem dubious which might hint at unknown issues with the diagonals filtering steps.
I'll investigate the bug you have reported further. For now all the tests were made in the browser so that's another possible cause for trouble.
Thanks.

**Comment by hubgit** [comment]
Strange - I first encountered the `RangeError` in a browser and thought it would be easier to reproduce with an example in Node! I can't think why a copy/pasted sequence would be different from data fetched from the server… (the error isn't thrown in every case, just with some sequences, for whatever reason).

Thanks for your work on this library, and don't feel any need to prioritise working on this error, I just thought it might be useful to report.

**Comment by ppillot** [comment]
I've fixed this bug. It was a special case in estring iteration terminations that was not properly accounted for.
Thanks for reporting this!
