### ISSUE TITLE
Feature request - synchronous align method

### ISSUE THREAD

**Issue by isohelio** [ppillot/biomsalign#4]
Hi,

Your library is really useful. Thank you for the significant effort you have put into this.

Is there any possibility of getting a synchronous align method. I cannot come up with a simple way to work with the Promise interface in my application (undoubtedly due to my abilities).

Alternatively guidance on how to call the align method without restructuring my highly traditional linear code would also be welcomed.

Many thanks,
Mike

**Comment by ppillot** [comment]
Thanks!
Could you paste some code about what you'd expect if the library were synchronous?
It's probably a matter of adding an `await` statement somewhere and I can help with this.

**Comment by ppillot** [comment]
```javascript
const result = await biomsa.align(
    ['SEQVENCE...', 'SEQWANCE...', 'CEQWANSE...'],
    {
        gapopen: -11,
        gapextend: -2,
        matrix: [[.....], [.....], ....],
        method: 'auto',
        type: 'auto',
        gapchar: '-',
        debug: false
    });
console.log(result);
```

**Comment by isohelio** [comment]
Thanks for the suggestion. This is basically the approach I have been taking.

The problem here is you have to wrap the await in an async function, and keep pushing that up the function call stack, till you no longer care about the async output.

I put together a working jsfiddle that shows the effect.

  https://jsfiddle.net/m5y6n794/11/

My code is inevitably a bit more involved than this. And you end up having to pay attention to a lot of async behaviour when its a bit of a distraction.

Thanks again.

**Comment by ppillot** [comment]
Right, that's a necessary evil. Alignments can take up to 1 min depending on the number of sequences and their sizes and when executed on the main thread, they are blocking.
At the moment, the library does not leverage webworkers to off load the main thread, but the async behaviour is a first step in that direction.
I don't think I should push development towards the goal of executing the computation synchronously.

In your example, it's possible to have only one async function (for example: https://jsfiddle.net/13oau65y/ where one function is returning a Promise instead of awaiting it). Depending on your code, it might be possible to isolate the place where the await is necessary.
I'd even add that it is desirable that not all the call stack is async, as it allows to perform other tasks while the computation is ongoing.

**Comment by isohelio** [comment]
Thanks, I will manage with this, I think I have adapted my code for minimal changes.

Proving very useful. I am mostly aligning 200 residue protein sequences.

Cheers,
Mike
